s = set()
Fruits = input("Enter fruits name:")
s.add(Fruits)
Fruits = input("Enter fruits name:")
s.add(Fruits)
Fruits = input("Enter fruits name:")
s.add(Fruits)
Fruits = input("Enter fruits name:")
s.add(Fruits)
Fruits = input("Enter fruits name:")
s.add(Fruits)
Fruits = input("Enter fruits name:")
s.add(Fruits)


print(s)